#!/usr/bin/env bash
# make-app.sh — wrap the SwiftPM release binary into dist/WhisprBro.app.
#
# SwiftPM alone can't produce an .app bundle, and menu-bar presence
# (LSUIElement) + the mic usage description require an Info.plist, so we
# assemble the bundle by hand and ad-hoc sign it.
#
# NOTE: ad-hoc signatures change on every build, so macOS may ask you to
# re-grant Accessibility/Input Monitoring after rebuilds (spec §8 gotcha —
# the permission watchdog lands in task-008).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$ROOT/dist/WhisprBro.app"

echo "building release…"
swift build -c release --package-path "$ROOT"

BIN="$ROOT/.build/release/WhisprBro"
[[ -x "$BIN" ]] || { echo "build product missing: $BIN" >&2; exit 1; }

FRAMEWORK="$ROOT/Vendor/llama.xcframework/macos-arm64/llama.framework"
[[ -d "$FRAMEWORK" ]] || { echo "missing $FRAMEWORK — run scripts/build-llama-xcframework.sh" >&2; exit 1; }

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" "$APP/Contents/Frameworks"
cp "$BIN" "$APP/Contents/MacOS/WhisprBro"

# Bundle the brand fonts (Archivo + IBM Plex Mono). ATSApplicationFontsPath in
# Info.plist auto-registers everything under Contents/Resources/Fonts at launch,
# so Brand.sans/Brand.mono resolve to the real faces (else they fall back to the
# system font).
if compgen -G "$ROOT/Fonts/*.ttf" > /dev/null; then
  mkdir -p "$APP/Contents/Resources/Fonts"
  cp "$ROOT"/Fonts/*.ttf "$APP/Contents/Resources/Fonts/"
else
  echo "warning: no fonts in $ROOT/Fonts — UI falls back to system fonts" >&2
fi

# App icon (brand doc §4, generated by scripts/make-icon.sh). CFBundleIconFile
# below points at it; without this the app shows the default blank icon.
if [[ -f "$ROOT/Assets/AppIcon.icns" ]]; then
  cp "$ROOT/Assets/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
else
  echo "warning: Assets/AppIcon.icns missing — run scripts/make-icon.sh (blank icon otherwise)" >&2
fi

# Ship the sha256 manifests so the in-app ModelManager can re-verify installed
# models on disk (Bundle.main/Contents/Resources/manifests — see ModelManager).
# Per-file with a warning so a missing manifest degrades gracefully (ModelManager
# handles it) instead of aborting the whole build under `set -euo pipefail`.
mkdir -p "$APP/Contents/Resources/manifests"
for m in models.sha256 models-vad.sha256 models-llm.sha256; do
  if [[ -f "$ROOT/scripts/$m" ]]; then
    cp "$ROOT/scripts/$m" "$APP/Contents/Resources/manifests/"
  else
    echo "warning: manifest $m not found — in-app model verify will show it missing" >&2
  fi
done

# The executable links @rpath/llama.framework (a dynamic framework). Embed it
# and point the rpath at the bundle's Frameworks dir so it resolves at runtime.
cp -R "$FRAMEWORK" "$APP/Contents/Frameworks/"
# Idempotent + loud: only add the rpath if absent, and fail if the add errors
# (a silently-missing rpath yields an app that can't load llama.framework).
if ! otool -l "$APP/Contents/MacOS/WhisprBro" | grep -q "@executable_path/../Frameworks"; then
  install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP/Contents/MacOS/WhisprBro"
fi

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleIdentifier</key>
	<string>com.micaxes.whispr-bro</string>
	<key>CFBundleName</key>
	<string>WhisprBro</string>
	<key>CFBundleDisplayName</key>
	<string>whispr-bro</string>
	<key>CFBundleExecutable</key>
	<string>WhisprBro</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>14.0</string>
	<key>LSUIElement</key>
	<true/>
	<key>ATSApplicationFontsPath</key>
	<string>Fonts</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>whispr-bro transcribes your speech entirely on this Mac. Audio never leaves the device.</string>
</dict>
</plist>
PLIST

# Sign with the stable self-signed "whispr-bro dev" identity if present, so
# TCC grants (Accessibility / Input Monitoring / Microphone) survive rebuilds.
# Without it, every ad-hoc rebuild changes the cdhash and macOS drops the
# grants (spec §8 gotcha). Run scripts/make-signing-cert.sh once to create it.
SIGN_ID="whispr-bro dev"
if security find-identity -v -p codesigning 2>/dev/null | grep -q "$SIGN_ID"; then
  echo "signing with stable identity: $SIGN_ID"
  # No hardened runtime: it enables Library Validation, which rejects our
  # self-signed llama.framework (no Team ID). Hardened runtime is only needed
  # for notarization, which this local dev build doesn't do.
  SIGN_ARGS=(--force --sign "$SIGN_ID")
else
  echo "WARNING: '$SIGN_ID' identity not found — falling back to ad-hoc."
  echo "  TCC grants will NOT survive rebuilds. Run scripts/make-signing-cert.sh once to fix."
  SIGN_ARGS=(--force --sign -)
fi
# Sign inside-out: the embedded framework before the app that contains it.
codesign "${SIGN_ARGS[@]}" "$APP/Contents/Frameworks/llama.framework"
codesign "${SIGN_ARGS[@]}" "$APP"

echo "signing authority:"
codesign -dv "$APP" 2>&1 | grep -E "Authority|Identifier" || true
echo "done: $APP"
echo "launch with: open '$APP'"
